version: '3.8'

networks:
  default:

services:
  db:
    image: mysql:5.7
    container_name: conference
    ports:
    - 3307:3307
    volumes:
    - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_USER: dockermysql
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: conference